### ISSUE TITLE
Order_by on datatable columns

### ISSUE THREAD

**Issue by ChiaCapone** [jellyfishsolutions/lynx#22]
Passing as argument of the createQueryBuilder() method an alias different from 'e' the 'order by' query executed internally to the fetchData() method gives the following error:

missing FROM-clause entry for table 'tableName'

because it considers 'e' as alias and not the one defined.

**Comment by Sprechen** [comment]
@ChiaCapone please resolve the issue as follow:
- add a new `alias` attribute to the `DatatableConfiguration`, with default value `'e'`.
- change the generated subqueries in order to use the `this.alias` instead of the `'e'`.
- add a new optional argument to the constructor in order to customize the value of the `alias`.

Thanks!!!

**Comment by Sprechen** [comment]
Fixed.
